# Generated by Django 5.0.4 on 2024-07-14 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_address_id_alter_coupon_id_alter_item_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='stripe_charge_id',
            new_name='khalti_charge_id',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='stripe_customer_id',
            new_name='khalti_customer_id',
        ),
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('J', 'Jersey'), ('SW', 'Sport wear'), ('OW', 'Outwear')], max_length=2),
        ),
    ]
