# Generated by Django 5.0.4 on 2024-07-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_stripe_charge_id_payment_khalti_charge_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='product/'),
        ),
    ]
